name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools-version: '30.0.3'
        ndk-version: '21.4.7075529'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: |
        ./gradlew assembleDebug --no-daemon --no-build-cache

    - name: List build outputs
      run: find . -name "*.apk" -type f

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: entropy-engine-app
        path: app/build/outputs/apk/debug/app-debug.apk
